spring:
  docker:
    compose:
      stop:
        command: down
  h2:
    console:
      enabled: true
  application:
    name: spring-ai
  datasource:
    url: jdbc:h2:file:S:/my_projects/Java_Projects/Spring-ai/sec02/springai/chatmemory;AUTO_SERVER=true
    driver-class-name: org.h2.Driver
    username: navneet
    password: 1234

  ai:
    vectorstore:
      qdrant:
        initialize-schema: true
        host: localhost
        port: 6334
        collection-name: oyenavneet
    openai:
      api-key: ${OPENAI_API_KEY}
    chat:
      memory:
        enabled: true
        repository:
          type: jdbc
          jdbc:
            initialize-schema: always
            schema: classpath:/schema/schema-h2db.sql

logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: DEBUG
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"